package apps.mrosystem.view;

import java.util.Arrays;
import java.util.Date;

import apps.mrosystem.model.User;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.VaadinSession;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Tree;
import com.vaadin.ui.TreeTable;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

public class AssetsView extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public static final String NAME = "ASSETS";
	
	private GridLayout mainContentContainer;
	
	@AutoGenerated
	private HorizontalLayout mainLayout;

	private SidePanel sidePanel;
		
	private String[] authorisedUsers = new String[]{"Admin","Technician","Planner","Management","Customer"};

	private User userData;
	
	private Table assetsTable;

	private TabSheet assetsTabSheet;

	private GridLayout assetsTableContainer;

	private VerticalLayout assetsTableControlContainer;

	private HorizontalSplitPanel assetsTableSplitPanel;

	private Tree assetsTableControlTree;

	private TextField assetsTableFilterTextField;

	public AssetsView() {
		userData = (User) VaadinSession.getCurrent().getAttribute("userData");
		if(userData != null){
			if(userData.isAuthorised(authorisedUsers)){
				buildMainLayout();
			}
			else{
				unauthorisedAccess();
			}
			
			setCompositionRoot(mainLayout);
		}
		// TODO add user code here
	}
	
	
	private HorizontalLayout unauthorisedAccess() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		setWidth("100.0%");
		setHeight("100.0%");
		
		sidePanel = new SidePanel();
		sidePanel.setActiveButton(NAME);
		sidePanel.setImmediate(false);
		sidePanel.setWidth("130px");
		sidePanel.setHeight("100.0%");
		mainLayout.addComponent(sidePanel);
		
		mainContentContainer = new GridLayout();
		mainContentContainer.setImmediate(false);
		mainContentContainer.setWidth("100.0%");
		mainContentContainer.setHeight("100.0%");
		mainContentContainer.setMargin(false);
		mainContentContainer.setRows(2);
		
		Label unauthorisedLabel = new Label();
		unauthorisedLabel.setImmediate(false);
		unauthorisedLabel.setWidth("-1px");
		unauthorisedLabel.setHeight("-1px");
		unauthorisedLabel.setValue("UNAUTHORISED ACCESS. You do not have access to view this page.");
		mainContentContainer.addComponent(unauthorisedLabel, 0, 0);
		
		mainLayout.addComponent(mainContentContainer);
		
		mainLayout.setExpandRatio(mainContentContainer, 1.0f);
		
		return mainLayout;
	}


	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// sidePanel
		sidePanel = new SidePanel();
		sidePanel.setActiveButton(NAME);
		sidePanel.setImmediate(false);
		sidePanel.setWidth("130px");
		sidePanel.setHeight("100.0%");
		mainLayout.addComponent(sidePanel);

	 		// mainContentContainer
		mainContentContainer = buildMainContentContainer();
		mainLayout.addComponent(mainContentContainer);
		
		mainLayout.setExpandRatio(mainContentContainer, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildMainContentContainer() {
		// common part: create layout
			
		assetsTable = new TreeTable();
		assetsTable.setSizeFull();
		assetsTable.setSelectable(true);
		assetsTable.setMultiSelect(true);
		assetsTable.setImmediate(true);
		
		
		assetsTableContainer = new GridLayout();
		assetsTableContainer.setImmediate(false);
		assetsTableContainer.setWidth("100.0%");
		assetsTableContainer.setHeight("100.0%");
		assetsTableContainer.setMargin(false);
		assetsTableContainer.setRows(1);
		assetsTableContainer.addComponent(assetsTable,0,0);

		
		assetsTable.addContainerProperty("NAME", String.class, "");
		assetsTable.addContainerProperty("DESCRIPTION", String.class, "");
		assetsTable.addItem(new Object[] {"All Projects", "HELLO"}, null);
		
		assetsTableFilterTextField = new TextField();
		assetsTableFilterTextField.setInputPrompt("Filter");
		assetsTableFilterTextField.setWidth("100%");
				
		assetsTableControlTree = new Tree("View Control");
		//assetsTableControlTree.setWidth("100%");
		assetsTableControlTree.setSizeFull();
		assetsTableControlTree.addItem(new Object[]{"HELLO"});
		
		
		assetsTableControlContainer = new VerticalLayout();
		assetsTableControlContainer.addStyleName("padding-small");
		assetsTableControlContainer.addComponent(assetsTableFilterTextField);
		assetsTableControlContainer.addComponent(assetsTableControlTree);
		
		
		assetsTableSplitPanel = new HorizontalSplitPanel();
		assetsTableSplitPanel.setSizeFull();
		assetsTableSplitPanel.setSplitPosition(200,Unit.PIXELS);
		assetsTableSplitPanel.addComponent(assetsTableControlContainer);
		assetsTableSplitPanel.addComponent(assetsTableContainer);
		
		
		assetsTabSheet = new TabSheet();
		assetsTabSheet.setHeight(100.0f, Unit.PERCENTAGE);
		assetsTabSheet.addStyleName(ValoTheme.TABSHEET_FRAMED);
		assetsTabSheet.addStyleName(ValoTheme.TABSHEET_PADDED_TABBAR);
		assetsTabSheet.addTab(assetsTableSplitPanel,"Table View");
		
		
		mainContentContainer = new GridLayout();
		mainContentContainer.setImmediate(false);
		mainContentContainer.setWidth("100.0%");
		mainContentContainer.setHeight("100.0%");
		mainContentContainer.setMargin(false);
		mainContentContainer.setRows(1);		
		mainContentContainer.addComponent(assetsTabSheet,0,0);

		
		
		
		
		

		
		return mainContentContainer;
	}

}
