package apps.mrosystem.view;

import java.util.Arrays;
import java.util.Date;

import apps.mrosystem.domain.User;
import apps.mrosystem.utils.Utils;
import apps.mrosystem.components.*;
import apps.mrosystem.controller.PlanningSchedulingHandler;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.FontAwesome;
import com.vaadin.server.VaadinSession;
import com.vaadin.server.Sizeable.Unit;
import com.vaadin.tapio.googlemaps.GoogleMap;
import com.vaadin.ui.Calendar;
//import com.vaadin.ui.Calendar;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TreeTable;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;


public class PlanningSchedulingView extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public static final String NAME = "PLANNINGSCHEDULING";
	
	private HorizontalLayout mainContentContainer;
	
	@AutoGenerated
	private HorizontalLayout mainLayout;

	private SidePanel sidePanel;
	
	private Label testLabel;
	private String[] authorisedUsers = new String[]{"Admin","Planner","Management"};

	private User userData;

	private PlanningSchedulingHandler handler;

	private TabSheet tabSheet;

	private VerticalLayout schedulingTab;

	private VerticalLayout buildSchedulingTab;

	private HorizontalLayout mapComontent;

	private HorizontalLayout calendarCompontent;

	private VerticalLayout technicianView;

	private VerticalLayout workOrderView;

	private GoogleMap map;

	private TreeTable technicianTable;

	private TreeTable workOrderTable;

	public PlanningSchedulingView() {

	}
	
	
	private HorizontalLayout unauthorisedAccess() {
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		setWidth("100.0%");
		setHeight("100.0%");
		
		sidePanel = new SidePanel();
		sidePanel.setActiveButton(NAME);
		sidePanel.setImmediate(false);
		sidePanel.setWidth("160px");
		sidePanel.setHeight("100.0%");
		mainLayout.addComponent(sidePanel);
		
		mainContentContainer = new HorizontalLayout();
		mainContentContainer.setImmediate(false);
		mainContentContainer.setWidth("100.0%");
		mainContentContainer.setHeight("100.0%");
		mainContentContainer.setMargin(false);
		
		Label unauthorisedLabel = new Label();
		unauthorisedLabel.setImmediate(false);
		unauthorisedLabel.setWidth("-1px");
		unauthorisedLabel.setHeight("-1px");
		unauthorisedLabel.setValue("UNAUTHORISED ACCESS. You do not have access to view this page.");
		mainContentContainer.addComponent(unauthorisedLabel);
		
		mainLayout.addComponent(mainContentContainer);
		
		mainLayout.setExpandRatio(mainContentContainer, 1.0f);
		
		return mainLayout;
	}

	public void enter(ViewChangeEvent event) {
		userData = (User) VaadinSession.getCurrent().getAttribute("userData");
		if(userData != null){
			if(userData.isAuthorised(authorisedUsers)){
				buildMainLayout();
			}
			else{
				unauthorisedAccess();
			}
			
			setCompositionRoot(mainLayout);
		}		
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// sidePanel
		sidePanel = new SidePanel();
		sidePanel.setActiveButton(NAME);
		sidePanel.setImmediate(false);
		sidePanel.setWidth("160px");
		sidePanel.setHeight("100.0%");
		mainLayout.addComponent(sidePanel);
		
		// mainContentContainer
		mainContentContainer = buildMainContentContainer();
		mainLayout.addComponent(mainContentContainer);
		
		mainLayout.setExpandRatio(mainContentContainer, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildMainContentContainer() {
		// common part: create layout
		mainContentContainer = new HorizontalLayout();
		mainContentContainer.setImmediate(false);
		mainContentContainer.setWidth("100.0%");
		mainContentContainer.setHeight("100.0%");
		mainContentContainer.setMargin(false);
		
		tabSheet = new TabSheet();
		tabSheet.setHeight(100.0f, Unit.PERCENTAGE);
/*			assetsTabSheet.addStyleName(ValoTheme.TABSHEET_FRAMED);*/
		tabSheet.addStyleName(ValoTheme.TABSHEET_PADDED_TABBAR);
		
		
		schedulingTab = buildSchedulingTab();
						
		tabSheet.addTab(schedulingTab, "Scheduling", FontAwesome.TABLE);

		
		mainContentContainer.addComponent(tabSheet);
		
		return mainContentContainer;
	}


	private VerticalLayout buildSchedulingTab() {
		schedulingTab = new VerticalLayout();
		schedulingTab.setWidth(100f, Unit.PERCENTAGE);
		schedulingTab.setHeight(100f, Unit.PERCENTAGE);
		
		calendarCompontent = buildCalendarCompontent();
		schedulingTab.addComponent(calendarCompontent);
		
		
		mapComontent = buildMapCompontent();
		schedulingTab.addComponent(mapComontent);
		
		
		return schedulingTab;
	}


	private HorizontalLayout buildMapCompontent() {
		mapComontent = new HorizontalLayout();
		mapComontent.setSizeFull();
		
		technicianView = buildTechnicianView();
		mapComontent.addComponent(technicianView);
		mapComontent.setExpandRatio(technicianView, 1);

		map = buildMap();
		mapComontent.addComponent(map);
		mapComontent.setExpandRatio(map, 4);

		workOrderView = buildWorkOrderView();
		mapComontent.addComponent(workOrderView);
		mapComontent.setExpandRatio(workOrderView, 1);

		
		return mapComontent;
	}


	

	private VerticalLayout buildTechnicianView() {
		technicianView = new VerticalLayout();
		technicianView.setWidth(100f, Unit.PERCENTAGE);
		technicianView.setHeight(100f, Unit.PERCENTAGE);
		
		technicianTable = new TreeTable();
		technicianTable.addStyleName("quiet");
		technicianTable.addStyleName("small");
		technicianTable.setSelectable(true);
		technicianTable.setMultiSelect(false);
		technicianTable.setImmediate(true);
		technicianTable.setColumnCollapsingAllowed(true);
		technicianTable.setWidth(100f, Unit.PERCENTAGE);
		technicianTable.setHeight(100f, Unit.PERCENTAGE);
		
		technicianView.addComponent(technicianTable);
		
		return technicianView;
	}

	private GoogleMap buildMap() {
		map = new GoogleMap("AIzaSyCOe-8GdvExrUOy8qzdoScoJhGRU8GYc8w", null, "english");
		map.setWidth(100f, Unit.PERCENTAGE);
		map.setHeight(100f, Unit.PERCENTAGE);
		
		return map;
	}

	private VerticalLayout buildWorkOrderView() {
		workOrderView = new VerticalLayout();
		workOrderView.setWidth(100f, Unit.PERCENTAGE);
		workOrderView.setHeight(100f, Unit.PERCENTAGE);
		
		
		workOrderTable = new TreeTable();
		workOrderTable.addStyleName("quiet");
		workOrderTable.addStyleName("small");
		workOrderTable.setSelectable(true);
		workOrderTable.setMultiSelect(false);
		workOrderTable.setImmediate(true);
		workOrderTable.setColumnCollapsingAllowed(true);
		workOrderTable.setWidth(100f, Unit.PERCENTAGE);
		workOrderTable.setHeight(100f, Unit.PERCENTAGE);
		
		workOrderView.addComponent(workOrderTable);
		
		return workOrderView;
	}




	private HorizontalLayout buildCalendarCompontent() {
		calendarCompontent = new HorizontalLayout();
		calendarCompontent.setWidth(100f, Unit.PERCENTAGE);
		calendarCompontent.setHeight(100f, Unit.PERCENTAGE);
		
		SchedulerComponent customerScheduler = new SchedulerComponent();
		
		calendarCompontent.addComponent(customerScheduler);
		
//		Date start = new Date();
//		Date end = Utils.addHoursToDate(start, 24);
//		System.out.println(start + "\t" + end);	
//		Calendar cal = new Calendar();
//		cal.setWidth("600px");
//		cal.setHeight("300px");
//		cal.setStartDate(start);
//		cal.setEndDate(end);
//		calendarCompontent.addComponent(cal);
		return calendarCompontent;
	}


	public String getName() {
		return NAME;
	}


	public void setHandler(PlanningSchedulingHandler handler) {
		this.handler = handler;
		
	}

}
