package apps.mrosystem.view;

import apps.mrosystem.model.User;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.server.Page;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.VaadinSession;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;

public class SidePanel extends CustomComponent implements View{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private CssLayout mainLayout;
	@AutoGenerated
	private CssLayout userControlContainer;
	@AutoGenerated
	private Button logoutButton;
	@AutoGenerated
	private Label usernameLabel;
	@AutoGenerated
	private Button settingButton;
	@AutoGenerated
	private Embedded profilePicture;
	
	private Label title;
	
	
	private String username;
	
	private User userData;
	
	private Button assetsButton;
	private Button inventoryButton;
	private Button workOrderButton;
	private Button planningSchedulingButton;
	private Button workforceButton;
	private Button adminButton;
	
	private Button usersButton;
	private Button reportsButton;
	private Button serviceRequestButton;
	private Button calendarButton;
	
	private Button customerButton;

	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SidePanel() {
		userData = (User) VaadinSession.getCurrent().getAttribute("userData");
		if(userData != null){
			buildMainLayout();
			setCompositionRoot(mainLayout);
		}
	}
	
	public void setActiveButton(String button){
		
		assetsButton.setStyleName("side-panel-nav-button assets-button");
		inventoryButton.setStyleName("side-panel-nav-button inventory-button");
		workOrderButton.setStyleName("side-panel-nav-button work-order-button");
		planningSchedulingButton.setStyleName("side-panel-nav-button planning-scheduling-button");
		workforceButton.setStyleName("side-panel-nav-button workforce-button");
		calendarButton.setStyleName("side-panel-nav-button calendar-button");
		serviceRequestButton.setStyleName("side-panel-nav-button service-request-button");
		adminButton.setStyleName("side-panel-nav-button admin-button");
		reportsButton.setStyleName("side-panel-nav-button reports-button");
		usersButton.setStyleName("side-panel-nav-button users-button");
		customerButton.setStyleName("side-panel-nav-button customer-button");
		
		switch (button) {
		case "ASSETS":
			assetsButton.setStyleName("side-panel-nav-button button-selected assets-button");
			break;
		case "INVENTORY":
			inventoryButton.setStyleName("side-panel-nav-button button-selected inventory-button");
			break;
		case "WORKORDERS":
			workOrderButton.setStyleName("side-panel-nav-button button-selected work-order-button");
			break;
		case "PLANNINGSCHEDULING":
			planningSchedulingButton.setStyleName("side-panel-nav-button button-selected planning-scheduling-button");
			break;
		case "WORKFORCE":
			workforceButton.setStyleName("side-panel-nav-button button-selected workforce-button");
			break;
		case "ADMIN":
			adminButton.setStyleName("side-panel-nav-button button-selected admin-button");
			break;
		case "CALENDAR":
			calendarButton.setStyleName("side-panel-nav-button button-selected calendar-button");
			break;
		case "SERVICEREQUEST":
			serviceRequestButton.setStyleName("side-panel-nav-button button-selected service-request-button");
			break;
		case "REPORTS":
			reportsButton.setStyleName("side-panel-nav-button button-selected reports-button");
			break;
		case "USERS":
			usersButton.setStyleName("side-panel-nav-button button-selected users-button");
			break;
		case "CUSTOMER":
			customerButton.setStyleName("side-panel-nav-button button-selected customer-button");
			break;
		}
	}
	
	private void initButtons(){
		initAdminButton();
		initAssetsButton();
		initCalendarButton();
		initInventoryButton();
		initPlanningSchedulingButton();
		initReportsButton();
		initServiceRequestButton();
		initUsersButton();
		initWorkforceButton();
		initWorkOrderButton();
		initCustomerButton();
		
	}

	@AutoGenerated
	private CssLayout buildMainLayout() {
		// common part: create layout
		initButtons();
		
		String userType = userData.getRole();
		
		switch (userType) {
		case "Admin":
			mainLayout = buildAdminLayout();
			break;
		case "Technician":
			mainLayout = buildTechnicianLayout();
			break;
		case "Planner":
			mainLayout = buildPlannerLayout();
			break;
		case "Quality":
			mainLayout = buildQualityAssurerLayout();
			break;
		case "Inspector":
			mainLayout = buildInspectorLayout();
			break;
		case "Manager":
			mainLayout = buildManagerLayout();
			break;
		case "Customer":
			mainLayout = buildCustomerLayout();
			break;
		}
		
		return mainLayout;
	}	

	
	private CssLayout buildAdminLayout(){
		CssLayout mainLayout = new CssLayout();
		mainLayout.addStyleName("side-panel-container");
		mainLayout.setImmediate(false);
		
		// top-level component properties

		//Title

		title = new Label("MRO System" + "<br><label class='small-text'>Admin Panel</label>");
		title.setContentMode(ContentMode.HTML);
		title.setStyleName("side-panel-main-title-label");
		
		mainLayout.addComponent(title);
		
		mainLayout.addComponent(adminButton);

		mainLayout.addComponent(assetsButton);

		mainLayout.addComponent(customerButton);

		mainLayout.addComponent(inventoryButton);

		mainLayout.addComponent(planningSchedulingButton);
		
		mainLayout.addComponent(reportsButton);

		mainLayout.addComponent(serviceRequestButton);
		
		mainLayout.addComponent(usersButton);

		mainLayout.addComponent(workOrderButton);
		
		mainLayout.addComponent(workforceButton);
		
		userControlContainer = buildUserControlContainer();
		mainLayout.addComponent(userControlContainer);
		
		
		return mainLayout;
	}
	
	private CssLayout buildTechnicianLayout(){
		CssLayout mainLayout = new CssLayout();
		mainLayout.addStyleName("side-panel-container");
		mainLayout.setImmediate(false);

		title = new Label("MRO System" + "<br><label class='small-text'>Technician Panel</label>");
		title.setContentMode(ContentMode.HTML);
		title.setStyleName("side-panel-main-title-label");
		
		mainLayout.addComponent(title);
		
		mainLayout.addComponent(assetsButton);

		mainLayout.addComponent(calendarButton);

		mainLayout.addComponent(customerButton);

		mainLayout.addComponent(inventoryButton);
		
		mainLayout.addComponent(workOrderButton);
		
		userControlContainer = buildUserControlContainer();
		mainLayout.addComponent(userControlContainer);
		
		
		return mainLayout;
	}
	
	private CssLayout buildManagerLayout(){
		CssLayout mainLayout = new CssLayout();
		mainLayout.addStyleName("side-panel-container");
		mainLayout.setImmediate(false);

		title = new Label("MRO System" + "<br><label class='small-text'>Manager Panel</label>");
		title.setContentMode(ContentMode.HTML);
		title.setStyleName("side-panel-main-title-label");
		
		mainLayout.addComponent(title);
		

		mainLayout.addComponent(assetsButton);

		mainLayout.addComponent(customerButton);

		mainLayout.addComponent(inventoryButton);

		mainLayout.addComponent(planningSchedulingButton);
		
		mainLayout.addComponent(reportsButton);

		mainLayout.addComponent(workOrderButton);
		
		mainLayout.addComponent(workforceButton);
		
		userControlContainer = buildUserControlContainer();
		mainLayout.addComponent(userControlContainer);
		
		return mainLayout;
	}
	
	private CssLayout buildCustomerLayout(){
		CssLayout mainLayout = new CssLayout();
		mainLayout.addStyleName("side-panel-container");
		mainLayout.setImmediate(false);
		
		title = new Label("MRO System" + "<br><label class='small-text'>Customer Panel</label>");
		title.setContentMode(ContentMode.HTML);
		title.setStyleName("side-panel-main-title-label");
		
		mainLayout.addComponent(title);

		mainLayout.addComponent(assetsButton);
		
		mainLayout.addComponent(serviceRequestButton);
		
		userControlContainer = buildUserControlContainer();
		mainLayout.addComponent(userControlContainer);
		
		return mainLayout;
	}
	
	private CssLayout buildPlannerLayout(){
		CssLayout mainLayout = new CssLayout();
		mainLayout.addStyleName("side-panel-container");
		mainLayout.setImmediate(false);

		title = new Label("MRO System" + "<br><label class='small-text'>Planner Panel</label>");
		title.setContentMode(ContentMode.HTML);
		title.setStyleName("side-panel-main-title-label");
		
		mainLayout.addComponent(title);

		mainLayout.addComponent(assetsButton);
		
		mainLayout.addComponent(customerButton);
		
		mainLayout.addComponent(inventoryButton);
		
		mainLayout.addComponent(planningSchedulingButton);
		
		mainLayout.addComponent(serviceRequestButton);
		
		mainLayout.addComponent(usersButton);
		
		mainLayout.addComponent(workOrderButton);
		
		userControlContainer = buildUserControlContainer();
		mainLayout.addComponent(userControlContainer);
		
		return mainLayout;
	}
	
	
	private CssLayout buildQualityAssurerLayout(){
		return null;
	}
	
	private CssLayout buildInspectorLayout(){
		return null;
	}
	
	@AutoGenerated
	private CssLayout buildUserControlContainer() {
		// common part: create layout
		userControlContainer = new CssLayout();
		userControlContainer.addStyleName("side-panel-user-control");
		userControlContainer.setImmediate(false);
		
		// usernameLabel     
		usernameLabel = new Label();
		usernameLabel.setValue("Welcome</br>" + "<b>" + userData.getFirstname() + "</b>");
		usernameLabel.setImmediate(false);
		usernameLabel.setStyleName("side-panel-username-label");
		usernameLabel.setContentMode(ContentMode.HTML);
		userControlContainer.addComponent(usernameLabel);
		
		// profilePicture
		profilePicture = new Embedded();
		profilePicture.setImmediate(false);
		profilePicture.setWidth("100.0%");
		profilePicture.setHeight("-1px");
		profilePicture.setStyleName("side-panel-profile-img");
		try{
			profilePicture.setSource(new ThemeResource(userData.getProfileImg()));
		}
		catch(Exception e){
			
		}
		
		
		profilePicture.setType(1);
		profilePicture.setMimeType("image/png");
		userControlContainer.addComponent(profilePicture);
		
		// settingButton
		settingButton = new Button();
		settingButton.setImmediate(false);
		settingButton.setWidth("30px");
		settingButton.setHeight("30px");
		settingButton.addStyleName("side-panel-setting-button");
		userControlContainer.addComponent(settingButton);
		
		// logoutButton
		logoutButton = new Button();
		logoutButton.setImmediate(true);
		logoutButton.setWidth("30px");
		logoutButton.setHeight("30px");
		logoutButton.addStyleName("side-panel-logout-button");
		userControlContainer.addComponent(logoutButton);

		logoutButton.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {logout();}
		});
		
		return userControlContainer;
	}
	
	private void logout(){
		   getSession().setAttribute("userData", null);
            // Refresh this view, should redirect to login view
           getUI().getNavigator().navigateTo("");
	}

	@Override
	public void enter(ViewChangeEvent event) {
		
	}

	
	private void initAssetsButton(){
		assetsButton = new Button();
		assetsButton.setStyleName("side-panel-nav-button assets-button");
		assetsButton.setCaption("Assets");
		assetsButton.setImmediate(true);
		assetsButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(AssetsView.NAME);
			}
		});

	}
	
	private void initInventoryButton(){
		inventoryButton = new Button();
		inventoryButton.setStyleName("side-panel-nav-button inventory-button");
		inventoryButton.setCaption("Inventory");
		inventoryButton.setImmediate(true);
		inventoryButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(InventoryView.NAME);
			}
		});

	}
	
	private void initWorkOrderButton(){
		workOrderButton = new Button();
		workOrderButton.setStyleName("side-panel-nav-button work-order-button");
		workOrderButton.setCaption("Work Orders");
		workOrderButton.setImmediate(true);
		workOrderButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(WorkOrdersView.NAME);
			}
		});

	}
	
	private void initPlanningSchedulingButton(){
		planningSchedulingButton = new Button();
		planningSchedulingButton.setStyleName("side-panel-nav-button planning-scheduling-button");
		planningSchedulingButton.setCaption("Planning");
		planningSchedulingButton.setImmediate(true);
		planningSchedulingButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(PlanningSchedulingView.NAME);
			}
		});

	}
	
	private void initWorkforceButton(){
		workforceButton = new Button();
		workforceButton.setStyleName("side-panel-nav-button workforce-button");
		workforceButton.setCaption("Workforce");
		workforceButton.setImmediate(true);
		workforceButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(WorkforceView.NAME);
			}
		});

	}

	
	private void initAdminButton(){
		adminButton = new Button();
		adminButton.setStyleName("side-panel-nav-button admin-button");
		adminButton.setCaption("Admin");
		adminButton.setImmediate(true);
		adminButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(AdminView.NAME);
			}
		});

	}
	
	private void initCalendarButton(){
		calendarButton = new Button();
		calendarButton.setStyleName("side-panel-nav-button calendar-button");
		calendarButton.setCaption("Calendar");
		calendarButton.setImmediate(true);
		calendarButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(CalendarView.NAME);
			}
		});

	}
	
	private void initServiceRequestButton(){
		serviceRequestButton = new Button();
		serviceRequestButton.setStyleName("side-panel-nav-button service-request-button");
		serviceRequestButton.setCaption("Work Request");
		serviceRequestButton.setImmediate(true);
		serviceRequestButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(ServiceRequestView.NAME);
			}
		});

	}
	
	private void initReportsButton(){
		reportsButton = new Button();
		reportsButton.setStyleName("side-panel-nav-button reports-button");
		reportsButton.setCaption("Reports");
		reportsButton.setImmediate(true);
		reportsButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(ReportsView.NAME);
			}
		});

	}
	
	private void initUsersButton(){
		usersButton = new Button();
		usersButton.setStyleName("side-panel-nav-button users-button");
		usersButton.setCaption("Users");
		usersButton.setImmediate(true);
		usersButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(UsersView.NAME);
			}
		});

	}
	
	private void initCustomerButton(){
		customerButton = new Button();
		customerButton.setStyleName("side-panel-nav-button customer-button");
		customerButton.setCaption("Customer");
		customerButton.setImmediate(true);
		customerButton.addClickListener(new ClickListener() {
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(CustomerView.NAME);
			}
		});

	}
}
