package apps.mrosystem.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class testView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout userDetailsLayout;
	@AutoGenerated
	private ComboBox titleComboBox;
	@AutoGenerated
	private TextField lastNameTextField;
	@AutoGenerated
	private TextField firstNameTextField;
	@AutoGenerated
	private Label userDetailsLabel;
	@AutoGenerated
	private VerticalLayout profilePictureControlLayout;
	@AutoGenerated
	private Button editProfilePictureButton;
	@AutoGenerated
	private Embedded profilePicture;
	private VerticalLayout prefLayout;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public testView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// profilePictureControlLayout
		profilePictureControlLayout = buildProfilePictureControlLayout();
		mainLayout.addComponent(profilePictureControlLayout);
		
		// userDetailsLayout
		userDetailsLayout = buildUserDetailsLayout();
		mainLayout.addComponent(userDetailsLayout);
		mainLayout.setExpandRatio(userDetailsLayout, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildProfilePictureControlLayout() {
		// common part: create layout
		profilePictureControlLayout = new VerticalLayout();
		profilePictureControlLayout.setImmediate(false);
		profilePictureControlLayout.setWidth("-1px");
		profilePictureControlLayout.setHeight("-1px");
		profilePictureControlLayout.setMargin(false);
		
		// profilePicture
		profilePicture = new Embedded();
		profilePicture.setImmediate(false);
		profilePicture.setWidth("-1px");
		profilePicture.setHeight("-1px");
		profilePicture.setSource(new ThemeResource(
				"img/component/embedded_icon.png"));
		profilePicture.setType(1);
		profilePicture.setMimeType("image/png");
		profilePictureControlLayout.addComponent(profilePicture);
		
		// editProfilePictureButton
		editProfilePictureButton = new Button();
		editProfilePictureButton.setCaption("Edit");
		editProfilePictureButton.setImmediate(true);
		editProfilePictureButton.setWidth("100.0%");
		editProfilePictureButton.setHeight("-1px");
		profilePictureControlLayout.addComponent(editProfilePictureButton);
		
		return profilePictureControlLayout;
	}

	@AutoGenerated
	private VerticalLayout buildUserDetailsLayout() {
		// common part: create layout
		userDetailsLayout = new VerticalLayout();
		userDetailsLayout.setImmediate(false);
		userDetailsLayout.setWidth("101.14%");
		userDetailsLayout.setHeight("-1px");
		userDetailsLayout.setMargin(false);
		
		// userDetailsLabel
		userDetailsLabel = new Label();
		userDetailsLabel.setImmediate(false);
		userDetailsLabel.setWidth("-1px");
		userDetailsLabel.setHeight("-1px");
		userDetailsLabel.setValue("User Details");
		userDetailsLayout.addComponent(userDetailsLabel);
		
		// firstNameTextField
		firstNameTextField = new TextField();
		firstNameTextField.setCaption("First Name");
		firstNameTextField.setDescription("Double click to edit.");
		firstNameTextField.setImmediate(false);
		firstNameTextField.setWidth("-1px");
		firstNameTextField.setHeight("-1px");
		userDetailsLayout.addComponent(firstNameTextField);
		
		// lastNameTextField
		lastNameTextField = new TextField();
		lastNameTextField.setCaption("Last Name");
		lastNameTextField.setImmediate(false);
		lastNameTextField.setWidth("-1px");
		lastNameTextField.setHeight("-1px");
		userDetailsLayout.addComponent(lastNameTextField);
		
		// titleComboBox
		titleComboBox = new ComboBox();
		titleComboBox.setCaption("Title");
		titleComboBox.setImmediate(false);
		titleComboBox.setWidth("-1px");
		titleComboBox.setHeight("-1px");
		userDetailsLayout.addComponent(titleComboBox);
		
		return userDetailsLayout;
	}



}
