package apps.mrosystem.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

public class testView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,22","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label Height;
	@AutoGenerated
	private Embedded image;
	@AutoGenerated
	private Label Weight;
	@AutoGenerated
	private Label image_label;
	@AutoGenerated
	private Label name_desc;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public testView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("500px");
		mainLayout.setHeight("500px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("500px");
		setHeight("500px");
		
		// name_desc
		name_desc = new Label();
		name_desc.setImmediate(false);
		name_desc.setWidth("-1px");
		name_desc.setHeight("-1px");
		name_desc.setValue("A00001 - Subsea Wellhead");
		mainLayout.addComponent(name_desc);
		
		// image_label
		image_label = new Label();
		image_label.setImmediate(false);
		image_label.setWidth("-1px");
		image_label.setHeight("-1px");
		image_label.setValue("Image");
		mainLayout.addComponent(image_label);
		
		// Weight
		Weight = new Label();
		Weight.setCaption("Weight");
		Weight.setImmediate(false);
		Weight.setDescription("product height");
		Weight.setWidth("100.0%");
		Weight.setHeight("-1px");
		Weight.setValue("80kg");
		mainLayout.addComponent(Weight);
		
		// image
		image = new Embedded();
		image.setImmediate(false);
		image.setWidth("-1px");
		image.setHeight("-1px");
		image.setSource(new ThemeResource("img/component/embedded_icon.png"));
		image.setType(1);
		image.setMimeType("image/png");
		mainLayout.addComponent(image);
		
		// Height
		Height = new Label();
		Height.setCaption("Weight");
		Height.setImmediate(false);
		Height.setDescription("product weight");
		Height.setWidth("-1px");
		Height.setHeight("-1px");
		Height.setValue("100m");
		mainLayout.addComponent(Height);
		
		// label_2
		label_2 = new Label();
		label_2.setCaption("Weight");
		label_2.setImmediate(false);
		label_2.setDescription("product weight");
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("100m");
		mainLayout.addComponent(label_2);
		
		return mainLayout;
	}

}
